# Generated by Django 5.2.4 on 2025-07-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_cupon', models.CharField(blank=True, max_length=50, null=True)),
                ('info_cupon', models.TextField(blank=True, null=True)),
                ('idtransaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_envio', models.CharField(max_length=50)),
                ('precio_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=100)),
                ('referencia', models.TextField()),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='banner',
            field=models.CharField(blank=True, max_length=5255, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='banner',
            field=models.CharField(blank=True, max_length=5255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='poster',
            field=models.CharField(blank=True, max_length=5255, null=True),
        ),
    ]
